title: Cyber Book 
favicon: favicon.ico
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  #instagram: matheuslaidler
  github: hithmast

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### analytics
google_analytics: G-KHGHKT689X
